version: '2'
services:
  influxdb:
    image: influxdb:alpine
    ports:
     - '8086:8086'
  telegraf:
    build: telegraf
    environment:
     SNMP_HOST: 192.168.15.1
     SNMP_PORT: 161
     SNMP_COMMUNITY: public
  grafana:
    image: grafana/grafana
    ports:
     - '3000:3000'
    environment:
     GF_SECURITY_ADMIN_PASSWORD: secret
